---
title: "TP_noté_Gaspard_Lamalle--Janodet"
author: "GLJ"
date: "2024-12-18"
output: html_document
---

## Question 1

Importation des données dans Rstudio.

```{r message=FALSE}
library(dplyr)
library(purrr)
library(stringr)

dt_exam <- list.files(path = "exam_data", full.names = TRUE, pattern = "*.csv") %>%
    set_names() %>%
    map_dfr(~ read.csv(.x),.id = "file_name") %>%
    mutate(file_name = str_remove(file_name, "exam_data/")) %>%
    mutate(file_name = str_remove(file_name, ".csv"))

str(dt_exam)

```

## Question 2

modélisation des ventes de FXD JET 100 en fonction des années.

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)

dt_exam %>%
  mutate(date = as.Date(date)) %>% 
  ggplot(aes(x = date, y = nb_de_ventes)) + 
  geom_point(aes(color = "Ventes"), size = 2, alpha = 0.7) +
  geom_area(aes(group = 1), fill = "darkgoldenrod", alpha = 0.2) +
  geom_hline(
    yintercept = median(dt_exam$nb_de_ventes), 
    linetype = "dashed", 
    colour = "red", 
    size = 0.5
  ) +  
  labs(
    x = "Années", 
    y = "Nombre de ventes", 
    title = "Évolution des ventes quotidiennes de FXD JET 100", 
    subtitle = "Analyse des tendances de ventes au fil du temps", 
    caption = "Source: Données internes"
  ) +
  theme_minimal(base_size = 0.1) + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12, colour = "black"),  
    axis.text.y = element_text(size = 12, colour = "black"),  
    axis.title.x = element_text(size = 12,colour = "black"), 
    axis.title.y = element_text(size = 12,colour = "black"),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5, colour = "black"),  
    plot.subtitle = element_text(size = 14, face = "italic", hjust = 0.5, colour = "black"),  
    plot.caption = element_text(size = 10, face = "italic", hjust = 1, colour = "grey40"),
    panel.grid.major = element_line(colour = "grey90", size = 0.5),  
    panel.grid.minor = element_blank(),  
    legend.position = "none"
  )
```




